name: CI

on: [push]

jobs:

    - name: "[name] ### ビルドジョブ ###"
      build:

        runs-on: ubuntu-latest

        steps:

            - name: "### チェックアウト ###"
              uses: actions/checkout@v1

            - name: "### Build script ###"
              run: yarn install && yarn tsc

            - name: "### Run test ###"
              run: yarn test
