name: CI

on: [push]

jobs:

    build-1:

        name: "ビルド: build-1"

        runs-on: ubuntu-latest

        steps:

            - name: "### チェックアウト ###"
              uses: actions/checkout@v1

            - name: "### Build script ###"
              run: yarn install && yarn tsc

            - name: "### Run test ###"
              run: yarn test

    build-2:

        name: "post build-1"

        needs: [ "build-1" ]

        runs-on: ubuntu-latest

        steps:

            - name: "### ビルド後の操作 ###"
              run: echo Ok.
