name: CI

on: [push]

jobs:

    build-1:

        name: "ビルド: build-1"

        runs-on: ubuntu-latest

        steps:

            - name: "### チェックアウト ###"
              uses: actions/checkout@v1

            - name: "### パッケージをインストールします ###"
              run: yarn install

            - name: "### アプリケーションをビルドします ###"
              run: yarn tsc

            - name: "### アプリケーションをテストします ###"
              run: yarn test

    deploy-1:

        name: "デプロイ: deploy-1"

        needs: [ "build-1" ]

        runs-on: ubuntu-latest

        steps:

            - name: "### アプリケーションをデプロイします ###"
              run: echo Ok.
